import { Component } from '@angular/core';

@Component({
  selector: 'app-film',
  templateUrl: './film.component.html',
  styleUrls: ['./film.component.scss']
})
export class FilmComponent {
  items:Array<any> = [
    {
      title: 'Kharon',
      image: '../assets/images/film/kharon.jpg',
      credit: 'Model builder',
      year: '2022',
      synopsis: `On a broken down spaceship, a grieving astronaut drifts through space and memory in order to understand his place in the universe.`,
      length: '19 minutes',
      imdb: 'https://www.imdb.com/title/tt15789174/',
      review: null,
      note: null,
    },
    {
      title: 'The Ringing Bell',
      image: '../assets/images/film/ringingbell.jpg',
      credit: 'Creature design',
      year: '2020',
      synopsis: "Judah is a young man with a condition - he dreams while he's still awake. His imagination makes it difficult for him to process the loss of his most important person, so when his cousin contacts him with a ridiculous scheme to get at that the riches of their eccentric Uncle Airmid who has disappeared, Judah agrees to go along with it.",
      length: '70 minutes',
      imdb: 'https://www.imdb.com/title/tt11687108/?ref_=nm_flmg_ardp_1',
      review: null,
      note: null,
    },
    {
      title: 'Lesser Beasts',
      image: '../assets/images/film/lesserbeasts.jpg',
      credit: 'Special effects',
      year: '2018',
      synopsis: `Casey T. Malone's feature debut "Lesser Beasts" is a film about four strangers’ lives and how they are entangled in a surreal and atmospheric journey to solve the puzzle they have all unwittingly become a part of. Nominated for Best Cinematography by Film Threat Magazine in 2019, and called "a moving photo novel [that] ranks with the greats."`,
      length: '86 minutes',
      imdb: 'https://www.imdb.com/title/tt8089668/?ref_=nm_knf_i2',
      review: 'https://filmthreat.com/reviews/lesser-beasts/',
      note: null,
    },
    {
      title: 'Clok',
      image: '../assets/images/film/clok.jpg',
      credit: 'Digital Matte Paintings',
      year: '2015',
      synopsis: "In this short multi-layered puzzle a researcher named Dylan Hensley believes he can conquer the passage of time by studying the movement of trees.",
      length: '7 minutes',
      imdb: 'http://www.imdb.com/title/tt4379996/',
      review: null,
      note: null,
    },
    {
      title: 'The Imprisonment of Henry Stoker',
      image: '../assets/images/film/stoker.jpg',
      credit: 'Story',
      year: '2013',
      synopsis: "The mathematician Henry Stoker awakes to find himself trapped inside of a surreal room with no clue as to how he arrived there. Something monstrous lurks behind one of the room's doors, and two figures taunt him as he attempts to open the safe he believes holds the key to his escape.",
      length: '14 minutes',
      imdb: 'http://www.imdb.com/title/tt3411770/',
      review: 'http://filmthreat.com/uncategorized/the-imprisonment-of-henry-stoker/',
      note: null,
    },
    {
      title: 'The Professor',
      image: '../assets/images/film/professor.jpg',
      credit: 'Graphics',
      year: '2013',
      synopsis: `Originally created for the H.P. Lovecraft Film Festival PDX 2013, this short teaches a valuable lesson for those collegiate individuals researching the dark arts and black magic.`,
      length: '2 minutes',
      imdb: 'http://www.imdb.com/title/tt2825718/',
      review: null,
      note: null,
    },
    {
      title: 'Coda Nera',
      image: '../assets/images/film/codanera1.jpg',
      credit: 'Graphics and Animation',
      year: '2012',
      synopsis: `The final installment in director Casey T. Malone's "Blood of the Witch Trilogy" (preceded by Blood of the Witch & Fortuna). The Witch has grown more powerful than ever. A coalition has formed to hunt her and bring her to justice. Dark allies are rallying to her side and eldritch forces have awakened in the forest. The hunters will become the hunted.`,
      length: '20 minutes',
      imdb: 'http://www.imdb.com/title/tt2515222/',
      review: 'http://filmthreat.com/uncategorized/coda-nera/',
      note: 'Part of a trilogy. For optimal enjoyment please watch with headphones or while hooked up to a speaker system.',
    },
    {
      title: 'Fortuna',
      image: '../assets/images/film/fortuna1.jpg',
      credit: 'Graphics',
      year: '2012',
      synopsis: `The macabre fairy tale is back with the prequel follow-up to "Blood of the Witch!" How did the witch become a witch? Where did that dastardly talking pumpkin come from? All this and more in the latest installment of The Blood of the Witch Trilogy. Official Selection of The H.P. Lovecraft Film Festival: Runner-Up "Best Short" Award`,
      length: '21 minutes',
      imdb: 'http://www.imdb.com/title/tt2328597/',
      review: 'http://filmthreat.com/uncategorized/fortuna/',
      note: 'Part of a trilogy. For optimal enjoyment please watch with headphones or while hooked up to a speaker system.',
    },
    {
      title: 'Blood of the Witch',
      image: '../assets/images/film/botw2.jpg',
      credit: 'Graphics',
      year: '2011',
      synopsis: `Murder, chaos, witches, pumpkins, poison apples, and the lot. This is a special production of a macabre fairy tale brought to you by Absolutely No1 Films. It is also the first in a trilogy.`,
      length: '19 minutes',
      imdb: 'http://www.imdb.com/title/tt2515222/',
      review: 'http://filmthreat.com/uncategorized/blood-of-the-witch/',
      note: 'Part of a trilogy. For optimal enjoyment please watch with headphones or while hooked up to a speaker system.',
    },
    {
      title: 'The Transient',
      image: '../assets/images/film/transient.jpg',
      credit: 'Producer and Illustrator',
      year: '2011',
      synopsis: `The story of one night in the life of comic book artist Billy Hogarth, and his strange journey into the unknown after being stuck inside his home for 5 years.`,
      length: '19 minutes',
      imdb: 'http://www.imdb.com/title/tt2035667/',
      review: null,
      note: null,
    }
  ];
}
